// Task #1:

// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:
// Input: s = "", t = "y"
// Output: "y"

// Example 3:
// Input: s = "a", t = "aa"
// Output: "a"

// Example 4:
// Input: s = "ae", t = "aea"
// Output: "a"

// Constraints:
// * 0 <= s.length <= 1000
// * t.length == s.length + 1
// * s and t consist of lower-case English letters.

let s0 = 'abcd';
let s1 = '';
let s2 = 'a';
let s3 = 'ae';

let t0 = 'abcde';
let t1 = 'y';
let t2 = 'aa';
let t3 = 'aea';

function getExtraLetter(s, t) {
	let extraLetter = t;
	for (let i = 0; i < s.length; i++) {
		extraLetter = extraLetter.replace(s[i], '');
	}
	return extraLetter;
}

console.log(`Example 1: ${getExtraLetter(s0, t0)}`);
console.log(getExtraLetter(s1, t1));
console.log(getExtraLetter(s2, t2));
console.log(getExtraLetter(s3, t3));